import { FormEvent, useEffect, useState } from 'react'
import { Plus, Search, Trash2, Pencil, X } from 'lucide-react'
import { supabase } from '../../lib/supabase'

type Field = { key:string; label:string; type?:'text'|'textarea'|'number'|'date'|'url'|'checkbox'|'select'; options?:string[]; required?:boolean }
type Props = { table:string; title:string; description:string; nameKey:string; fields:Field[]; defaults?:Record<string,unknown> }
export default function AdminCrudPage({table,title,description,nameKey,fields,defaults={}}:Props){
 const [rows,setRows]=useState<any[]>([]),[editing,setEditing]=useState<any|null>(null),[open,setOpen]=useState(false),[search,setSearch]=useState(''),[message,setMessage]=useState('')
 async function load(){const {data,error}=await supabase.from(table).select('*').order('created_at',{ascending:false}); if(error)setMessage(error.message); setRows(data??[])}
 useEffect(()=>{load()},[table])
 function add(){setEditing({...defaults});setOpen(true)}
 function edit(row:any){setEditing({...row});setOpen(true)}
 async function save(e:FormEvent){e.preventDefault(); if(!editing)return; const payload:any={...editing}; delete payload.id; delete payload.created_at; delete payload.updated_at; const q=editing.id?supabase.from(table).update(payload).eq('id',editing.id):supabase.from(table).insert(payload); const {error}=await q; setMessage(error?`Erro: ${error.message}`:'Salvo com sucesso.'); if(!error){setOpen(false);setEditing(null);await load()}}
 async function remove(id:string){if(!confirm('Excluir este item?'))return;const {error}=await supabase.from(table).delete().eq('id',id);setMessage(error?error.message:'Item excluído.');if(!error)load()}
 const filtered=rows.filter(r=>String(r[nameKey]??'').toLowerCase().includes(search.toLowerCase()))
 return <div><div className="admin-topbar"><div><span className="eyebrow">GERENCIAMENTO</span><h1>{title}</h1><p className="muted">{description}</p></div><button className="button" onClick={add}><Plus size={17}/> Novo</button></div>{message&&<div className="admin-message admin-panel">{message}</div>}<section className="admin-panel"><div className="admin-toolbar"><label className="search-box"><Search size={16}/><input placeholder="Pesquisar" value={search} onChange={e=>setSearch(e.target.value)}/></label><span>{filtered.length} itens</span></div><div className="admin-list-table">{filtered.map(r=><div className="admin-list-row" key={r.id}><div><strong>{r[nameKey]}</strong><span>{r.category||r.status||r.institution||''}</span></div><div><button className="icon-btn" onClick={()=>edit(r)}><Pencil size={16}/></button><button className="icon-btn danger" onClick={()=>remove(r.id)}><Trash2 size={16}/></button></div></div>)}{!filtered.length&&<div className="empty-state">Nenhum item cadastrado.</div>}</div></section>{open&&editing&&<div className="modal-backdrop"><form className="modal-card admin-form" onSubmit={save}><div className="modal-head"><h2>{editing.id?'Editar':'Novo'} {title.toLowerCase()}</h2><button type="button" className="icon-btn" onClick={()=>setOpen(false)}><X/></button></div>{fields.map(f=><label key={f.key} className={f.type==='textarea'?'wide':''}>{f.label}{f.type==='textarea'?<textarea rows={5} required={f.required} value={editing[f.key]??''} onChange={e=>setEditing({...editing,[f.key]:e.target.value})}/>:f.type==='checkbox'?<input type="checkbox" checked={Boolean(editing[f.key])} onChange={e=>setEditing({...editing,[f.key]:e.target.checked})}/>:f.type==='select'?<select value={editing[f.key]??f.options?.[0]??''} onChange={e=>setEditing({...editing,[f.key]:e.target.value})}>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:<input type={f.type||'text'} required={f.required} value={editing[f.key]??''} onChange={e=>setEditing({...editing,[f.key]:f.type==='number'?Number(e.target.value):e.target.value})}/>}</label>)}<div className="form-actions wide"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="button">Salvar</button></div></form></div>}</div>
}
